component_depth: 8

languages:
  - name: cpp
    
    production:
      include:
        - /lib/src/.*\.cpp
        - /lib/include/sway/.*\.h
      exclude:
        - /lib/tests/.*

    test:
      include:
        - /lib/tests/.*\.cpp
