component_depth: 8

languages:
  - name: cpp
    
    production:
      include:
        - /lib/cxx/src/.*\.cpp
        - /lib/cxx/include/sway/.*\.h
      exclude:
        - /lib/cxx/tests/.*

    test:
      include:
        - /lib/cxx/tests/.*\.cpp
