component_depth: 8

languages:
  - name: cpp
    
    production:
      include:
        - /lib/cpp/src/.*\.cpp
        - /lib/cpp/include/sway/.*\.h
      exclude:
        - /lib/cpp/tests/.*

    test:
      include:
        - /lib/cpp/tests/.*\.cpp
